config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'
  resources :poems do
    resources :replies
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poem.rb
class Poem < ApplicationRecord
  has_many :replies, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :poem
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  def index
    @poems = Poem.all
  end

  def show
    @poem = Poem.find(params[:id])
  end

  def new
    @poem = Poem.new
  end

  def edit
    @poem = Poem.find(params[:id])
  end

  def create
    @poem = Poem.new(poem_params)

    if @poem.save
    redirect_to @poem
    else
      render 'new'
    end
  end

  def update
    @poem = Poem.find(params[:id])
    if @poem.update(poem_params)
      redirect_to @poem
    else
      render 'edit'
    end
  end

  def destroy
    @poem = Poem.find(params[:id])
    @poem.destroy

    redirect_to poems_path
  end

  private
    def poem_params
      params.require(:poem).permit(:title, :body)
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  def create
    @poem = Poem.find(params[:poem_id])
    @reply = @poem.replies.create(reply_params)
    redirect_to poem_path(@poem)
  end

  def destroy
    @poem = Poem.find(params[:poem_id])
    @reply = @poem.replies.find(params[:id])
    @reply.destroy
    redirect_to poem_path
  end

  private
    def reply_params
      params.require(:reply).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poetry</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/poems/_form.html.erb
<%= form_with model: @poem, local: true do |form| %>

  <% if @poem.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@poem.errors.count, "error") %> prohibited
        this poem from being saved:
      </h2>
      <ul>
        <% @poem.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/poems/edit.html.erb
<h1>Edit Poem</h1>
<%= render 'form' %>
<%= link_to 'Back', poems_path %>

app/views/poems/index.html.erb
<h1>Listing poems</h1>
<%= link_to 'New poem', new_poem_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @poems.each do |poem| %>
    <tr>
      <td><%= poem.title %></td>
      <td><%= poem.body %></td>
      <td><%= link_to 'Show', poem_path(poem) %></td>
      <td><%= link_to 'Edit', edit_poem_path(poem) %></td>
      <td><%= link_to 'Destroy', poem_path(poem),
              method: :delete,
              data: { confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

app/views/poems/new.html.erb
<h1>New Poem</h1>

<%= render 'form' %>
<%= link_to 'Back', poems_path %>

app/views/poems/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @poem.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @poem.body %>
</p>

<h2>Comments</h2>
<%= render @poem.replies %>

<h2>Add a comment:</h2>
<%= render 'replies/form' %>

<%= link_to 'Edit', edit_poem_path(@poem) %> |
<%= link_to 'Back', poems_path %>

app/views/replies/_form.html.erb
<%= form_with(model: [ @poem, @poem.replies.build ]) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/replies/_reply.html.erb
<p>
  <strong>Commenter:</strong>
  <%= reply.commenter %>
</p>

<p>
  <strong>Reply:</strong>
  <%= reply.body %>
</p>

<p>
  <%= link_to 'Delete Reply', [reply.poem, reply],
              method: :delete,
              data: { confirm: 'Are you sure?'}  %>
</p>

app/views/welcome/index.html.erb
<h1>Hello, Everyone!</h1>
<%= link_to 'My Blog', controller: 'poems' %>